# Generated by Django 4.1.2 on 2022-11-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='День недели')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер недели')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(max_length=10, verbose_name='Номер группы'),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10, verbose_name='Номер группы')),
                ('update_time', models.TimeField(auto_now=True)),
                ('week1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable1', to='main.week', verbose_name='Первая неделя')),
                ('week2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable2', to='main.week', verbose_name='Вторая неделя')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер пары')),
                ('time', models.CharField(max_length=20, verbose_name='Время пары')),
                ('type', models.CharField(max_length=25, verbose_name='Тип пары')),
                ('name', models.CharField(max_length=100, verbose_name='Название курса')),
                ('note', models.TextField(default='', verbose_name='Заметки')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.day', verbose_name='День')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='Информация')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson', verbose_name='Пара')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.week', verbose_name='Неделя'),
        ),
    ]
