# Generated by Django 4.1.2 on 2022-11-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_day_week_alter_user_group_timetable_lesson_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
