# Generated by Django 4.1.2 on 2022-11-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_timetable_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_elder',
            field=models.BooleanField(default=False, verbose_name='Стороста'),
        ),
    ]
